# Generated by Django 5.1.15 on 2026-03-30 19:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrackedEmail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.TextField(blank=True, default='')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('gmail_message_id', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['gmail_message_id'], name='email_track_gmail_m_68d441_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrackedLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_hash', models.CharField(db_index=True, max_length=16)),
                ('original_url', models.URLField(max_length=2048)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='email_tracker.trackedemail')),
            ],
            options={
                'unique_together': {('email', 'link_hash')},
            },
        ),
        migrations.CreateModel(
            name='TrackedRecipient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_address', models.EmailField(max_length=254)),
                ('tracking_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='email_tracker.trackedemail')),
            ],
        ),
        migrations.CreateModel(
            name='OpenEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opens', to='email_tracker.trackedrecipient')),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='ClickEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='email_tracker.trackedlink')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='email_tracker.trackedrecipient')),
            ],
            options={
                'ordering': ['-clicked_at'],
            },
        ),
    ]
