# Generated by Django 5.1.15 on 2026-03-22 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sending_email',
            field=models.EmailField(blank=True, help_text='Email address to send campaign emails from (must be configured as Send As alias in Gmail)', max_length=254),
        ),
    ]
