# Generated by Django 5.1.15 on 2026-03-23 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_sending_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='sending_email',
        ),
    ]
