# Generated by Django 5.1.15 on 2026-03-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_sending_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(
                choices=[('admin', 'Admin'), ('agent', 'Agent'), ('student', 'Student')],
                default='agent',
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='stripe_customer_id',
            field=models.CharField(blank=True, help_text='For future payment integration', max_length=255),
        ),
    ]
