services:
  web:
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings_production
    restart: always

  celery:
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings_production
    restart: always

  celery-beat:
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings_production
    restart: always

  db:
    restart: always

  redis:
    restart: always

  nginx:
    restart: always
    volumes:
      - ./nginx/nginx-ssl.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
