services:
  web:
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings_production
      - META_APP_ID=${META_APP_ID}
      - META_APP_SECRET=${META_APP_SECRET}
      - META_WEBHOOK_VERIFY_TOKEN=${META_WEBHOOK_VERIFY_TOKEN}
    restart: always

  celery:
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings_production
      - META_APP_ID=${META_APP_ID}
      - META_APP_SECRET=${META_APP_SECRET}
      - META_WEBHOOK_VERIFY_TOKEN=${META_WEBHOOK_VERIFY_TOKEN}
    restart: always

  celery-beat:
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings_production
    restart: always

  db:
    restart: always

  redis:
    restart: always

  nginx:
    restart: always
    volumes:
      - ./nginx/nginx-ssl.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /opt/condo-search/dist:/opt/condo-search/dist:ro
