# Generated by Django 5.1.15 on 2026-03-22 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('contacts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='accounts.team')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('delay_days', models.PositiveIntegerField(default=0)),
                ('delay_hours', models.PositiveIntegerField(default=0)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField(help_text='HTML email body. Use {{first_name}}, {{agent_name}}, {{agent_phone}} for merge fields.')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='campaign_videos/')),
                ('video_thumbnail', models.ImageField(blank=True, null=True, upload_to='campaign_thumbnails/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='campaigns.campaign')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CampaignEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('paused_reason', models.CharField(blank=True, max_length=100)),
                ('next_send_at', models.DateTimeField(null=True)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='campaigns.campaign')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='contacts.contact')),
                ('current_step', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaigns.campaignstep')),
            ],
        ),
    ]
