# Generated by Django 6.0.3 on 2026-04-04 16:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0003_alter_contactactivity_activity_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="collaborators",
            field=models.ManyToManyField(
                blank=True,
                help_text="Team members who can also view and interact with this contact.",
                related_name="collaborated_contacts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
