# Generated by Django 5.1.15 on 2026-04-24 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_contact_collaborators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='source',
            field=models.CharField(choices=[('landing_page', 'Landing Page'), ('manual', 'Manual Entry'), ('referral', 'Referral'), ('zillow', 'Zillow'), ('realtor', 'Realtor.com'), ('subdivision_form', 'Subdivision Page (Track 1)'), ('condo_quiz', 'Condo Quiz (Track 2)'), ('lead_magnet_relocation', 'Lead Magnet — Relocation Guide'), ('lead_magnet_condo', 'Lead Magnet — Condo Cheat Sheet'), ('bio_splitter', 'IG Bio Splitter Page'), ('other', 'Other')], default='manual', max_length=50),
        ),
    ]
