# Generated by Django 5.1.15 on 2026-03-23 00:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_remove_user_sending_email'),
        ('contacts', '0002_tag_contact_tag_objects'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('pdf_file', models.FileField(upload_to='signatures/originals/')),
                ('signed_pdf', models.FileField(blank=True, upload_to='signatures/signed/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('viewed', 'Viewed'), ('completed', 'Completed'), ('declined', 'Declined'), ('expired', 'Expired')], default='draft', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('pdf_hash', models.CharField(blank=True, help_text='SHA-256 hash of signed PDF', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signature_documents', to='contacts.contact')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signature_documents', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signature_documents', to='accounts.team')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentSigner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(blank=True, help_text='e.g. Buyer, Seller', max_length=100)),
                ('access_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('opened', 'Opened'), ('completed', 'Completed'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signers', to='signatures.document')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_type', models.CharField(choices=[('signature', 'Signature'), ('initials', 'Initials'), ('text', 'Text'), ('date', 'Date'), ('checkbox', 'Checkbox')], max_length=20)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('page', models.PositiveIntegerField()),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('required', models.BooleanField(default=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='signatures.document')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='signatures.documentsigner')),
            ],
            options={
                'ordering': ['page', 'y', 'x'],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Document Created'), ('sent', 'Document Sent'), ('opened', 'Document Opened'), ('field_signed', 'Field Signed'), ('completed', 'Signing Completed'), ('declined', 'Signing Declined'), ('downloaded', 'Document Downloaded')], max_length=20)),
                ('detail', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='signatures.document')),
                ('signer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='signatures.documentsigner')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('pdf_file', models.FileField(upload_to='signatures/templates/')),
                ('signer_roles', models.JSONField(blank=True, default=list, help_text='List of role names, e.g. ["Buyer", "Seller"]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signature_templates', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signature_templates', to='accounts.team')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='signatures.documenttemplate'),
        ),
        migrations.CreateModel(
            name='SignerFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(help_text='Text value or base64 signature image')),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('field', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='value', to='signatures.documentfield')),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='signatures.documentsigner')),
            ],
        ),
        migrations.CreateModel(
            name='TemplateField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_type', models.CharField(choices=[('signature', 'Signature'), ('initials', 'Initials'), ('text', 'Text'), ('date', 'Date'), ('checkbox', 'Checkbox')], max_length=20)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('signer_role', models.CharField(help_text='Role name this field is assigned to', max_length=100)),
                ('page', models.PositiveIntegerField()),
                ('x', models.FloatField(help_text='X position as percentage of page width')),
                ('y', models.FloatField(help_text='Y position as percentage of page height')),
                ('width', models.FloatField(help_text='Width as percentage of page width')),
                ('height', models.FloatField(help_text='Height as percentage of page height')),
                ('required', models.BooleanField(default=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='signatures.documenttemplate')),
            ],
            options={
                'ordering': ['page', 'y', 'x'],
            },
        ),
    ]
