# Generated by Django 5.1.15 on 2026-03-23 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentfield',
            name='field_type',
            field=models.CharField(choices=[('signature', 'Signature'), ('initials', 'Initials'), ('name', 'Name'), ('text', 'Text'), ('date', 'Date'), ('checkbox', 'Checkbox')], max_length=20),
        ),
        migrations.AlterField(
            model_name='templatefield',
            name='field_type',
            field=models.CharField(choices=[('signature', 'Signature'), ('initials', 'Initials'), ('name', 'Name'), ('text', 'Text'), ('date', 'Date'), ('checkbox', 'Checkbox')], max_length=20),
        ),
    ]
