# Generated by Django 5.1.15 on 2026-03-24 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatures', '0002_alter_documentfield_field_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentfield',
            name='prefill_value',
            field=models.TextField(blank=True, help_text='Pre-filled value set by sender on the prepare page'),
        ),
    ]
