# Generated by Django 5.1.15 on 2026-03-24 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatures', '0003_documentfield_prefill_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentfield',
            name='read_only',
            field=models.BooleanField(default=False, help_text='If true, signer sees the value but cannot edit it'),
        ),
    ]
