# Generated by Django 5.1.15 on 2026-03-24 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signatures', '0004_documentfield_read_only'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentfield',
            name='prefill_value',
        ),
        migrations.RemoveField(
            model_name='documentfield',
            name='read_only',
        ),
    ]
