# Generated by Django 5.1.15 on 2026-03-24 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatures', '0005_remove_documentfield_prefill_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentfield',
            name='prefill_value',
            field=models.TextField(blank=True, help_text='Pre-filled value set by sender on the prepare page'),
        ),
        migrations.AddField(
            model_name='documentfield',
            name='read_only',
            field=models.BooleanField(default=False, help_text='If true, signer sees the value but cannot edit it'),
        ),
    ]
