# Generated by Django 5.1.15 on 2026-03-25 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatures', '0007_document_is_archived_document_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('pdf_file', models.FileField(upload_to='signatures/originals/')),
                ('page_start', models.PositiveIntegerField(help_text='First page number in the merged PDF (1-based)')),
                ('page_end', models.PositiveIntegerField(help_text='Last page number in the merged PDF (1-based)')),
                ('order', models.PositiveIntegerField(default=0)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_files', to='signatures.document')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
