# Generated by Django 5.1.15 on 2026-03-26 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signatures', '0008_documentfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='is_archived',
        ),
        migrations.RemoveField(
            model_name='document',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='documentfield',
            name='prefill_value',
        ),
        migrations.RemoveField(
            model_name='documentfield',
            name='read_only',
        ),
        migrations.DeleteModel(
            name='DocumentFile',
        ),
    ]
