# Generated by Django 5.1.15 on 2026-03-26 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatures', '0009_remove_document_is_archived_remove_document_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='List of tag strings'),
        ),
        migrations.AddField(
            model_name='documentfield',
            name='prefill_value',
            field=models.TextField(blank=True, help_text='Pre-filled value set by sender on the prepare page'),
        ),
        migrations.AddField(
            model_name='documentfield',
            name='read_only',
            field=models.BooleanField(default=False, help_text='If true, signer sees the value but cannot edit it'),
        ),
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('pdf_file', models.FileField(upload_to='signatures/originals/')),
                ('page_start', models.PositiveIntegerField(help_text='First page number in the merged PDF (1-based)')),
                ('page_end', models.PositiveIntegerField(help_text='Last page number in the merged PDF (1-based)')),
                ('order', models.PositiveIntegerField(default=0)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_files', to='signatures.document')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
