# Generated by Django 5.1.15 on 2026-03-26 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatures', '0010_document_is_archived_document_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttemplate',
            name='page_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of pages in the template PDF'),
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='text_fingerprint',
            field=models.TextField(blank=True, help_text='Extracted text from PDF for auto-matching'),
        ),
    ]
