# Generated by Django 5.1.15 on 2026-03-31 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatures', '0011_documenttemplate_page_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentfield',
            name='bold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documentfield',
            name='font_size',
            field=models.PositiveIntegerField(default=0, help_text='Font size in pt (0 = auto)'),
        ),
        migrations.AddField(
            model_name='documentfield',
            name='italic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='templatefield',
            name='bold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='templatefield',
            name='font_size',
            field=models.PositiveIntegerField(default=0, help_text='Font size in pt (0 = auto)'),
        ),
        migrations.AddField(
            model_name='templatefield',
            name='italic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='templatefield',
            name='prefill_value',
            field=models.CharField(blank=True, default='', help_text='Pre-filled text value', max_length=500),
        ),
        migrations.AddField(
            model_name='templatefield',
            name='read_only',
            field=models.BooleanField(default=False, help_text='If true, signer sees the value but cannot edit it'),
        ),
    ]
