# Generated by Django 6.0.3 on 2026-04-04 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0005_add_user_avatar"),
        ("campaigns", "0003_campaignstep_video"),
        ("contacts", "0004_contact_collaborators"),
    ]

    operations = [
        migrations.CreateModel(
            name="KeywordTrigger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("keyword", models.CharField(max_length=100)),
                (
                    "match_type",
                    models.CharField(
                        choices=[
                            ("exact", "Exact Match"),
                            ("contains", "Contains"),
                            ("starts_with", "Starts With"),
                        ],
                        default="contains",
                        max_length=20,
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("instagram", "Instagram"),
                            ("facebook", "Facebook"),
                            ("both", "Both"),
                        ],
                        default="both",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("reply_text", models.TextField(help_text="Auto-reply message body")),
                (
                    "reply_link",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="Optional link to include (PDF, video, landing page)",
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
                ("create_contact", models.BooleanField(default=True)),
                ("notify_agent", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="keyword_triggers",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="keyword_triggers",
                        to="accounts.team",
                    ),
                ),
            ],
            options={
                "ordering": ["keyword"],
            },
        ),
        migrations.CreateModel(
            name="SocialAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[("instagram", "Instagram"), ("facebook", "Facebook")],
                        max_length=20,
                    ),
                ),
                ("page_id", models.CharField(max_length=100)),
                ("page_name", models.CharField(max_length=255)),
                (
                    "access_token",
                    models.TextField(help_text="Encrypted Page Access Token"),
                ),
                (
                    "instagram_account_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Instagram Business Account ID (for IG-specific calls)",
                        max_length=100,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("webhook_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_accounts",
                        to="accounts.team",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("team", "page_id")},
            },
        ),
        migrations.CreateModel(
            name="MessageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sender_id", models.CharField(max_length=100)),
                (
                    "sender_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("message_text", models.TextField()),
                ("platform", models.CharField(max_length=20)),
                ("reply_sent", models.BooleanField(default=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "contact_created",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="social_messages",
                        to="contacts.contact",
                    ),
                ),
                (
                    "trigger_matched",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="message_logs",
                        to="social.keywordtrigger",
                    ),
                ),
                (
                    "social_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="social.socialaccount",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
