# Generated by Django 5.1.15 on 2026-04-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='access_token',
            field=models.TextField(help_text='Page Access Token from Meta OAuth'),
        ),
    ]
